- id: bump-version
  name: Bump version
  description: Bump version file when code changes
  entry: hooks/bump_version.sh
  language: script
  exclude: (.github/)|(README.md)|(LICENSE)|(.pre-commit-config.yaml)|(.yamllint.yaml)
  require_serial: true
    